### ISSUE TITLE
downloaded youtube-dl doesn't have execute permission

### ISSUE THREAD

**Issue by insanity54** [skt-t1-byungi/ytdl-run#1]
I noticed that ytdl-run has an installation script, install.js. This script is supposed to install the youtube-dl binary if it doesn't exist on the local system, however it doesn't seem to function properly. 

Node v8.11.3 on Linux

```
ytdl-run@0.1.2 postinstall /home/node/app
node ./install.js

installing youtube-dl...
(node:18) UnhandledPromiseRejectionWarning: Error: spawn EACCES
    at _errnoException (util.js:992:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at module.exports (/home/node/app/node_modules/execa/index.js:204:26)
    at /home/node/app/install.js:14:35
    at <anonymous>
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It looks like youtube-dl is downloaded successfully, but the file permissions are wrong. 

```
-rw-r--r-- 1 roger roger 1702856 Oct  5 03:12 bin/youtube-dl
```

the owner needs rwx

I created a PR which addresses this issue https://github.com/skt-t1-byungi/ytdl-run/pull/2

**Comment by skt-t1-byungi** [comment]
It's my personal use, so I haven't tested it in many environments. Thanks for letting me know!
